const $=id=>document.getElementById(id);
let products=[];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function euro(v){return new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v||0));}
function msg(text,type='success',id='bar-admin-message'){const b=$(id);b.textContent=text;b.className=`message show ${type}`;}
function storagePathFromUrl(url){if(!url)return null;const marker='/storage/v1/object/public/bar-immagini/';const i=url.indexOf(marker);return i<0?null:decodeURIComponent(url.slice(i+marker.length));}
async function session(){const {data}=await db.auth.getSession();const on=Boolean(data.session);$('bar-login-box').classList.toggle('hidden',on);$('bar-dashboard').classList.toggle('hidden',!on);if(on){await loadProducts();await loadBookings();}}
async function login(){const {error}=await db.auth.signInWithPassword({email:$('bar-login-email').value.trim(),password:$('bar-login-password').value});if(error)return msg('Accesso non riuscito: '+error.message,'error','bar-login-message');session();}
function resetForm(){$('bar-product-id').value='';$('bar-product-name').value='';$('bar-product-description').value='';$('bar-product-price').value='';$('bar-product-order').value='0';$('bar-product-active').checked=true;}
async function saveProduct(e){e.preventDefault();const id=$('bar-product-id').value;const payload={nome:$('bar-product-name').value.trim(),descrizione:$('bar-product-description').value.trim()||null,prezzo:Number($('bar-product-price').value||0),ordine:Number($('bar-product-order').value||0),attivo:$('bar-product-active').checked};if(!payload.nome)return msg('Inserisci il nome.','error');const q=id?db.from('bar_prodotti').update(payload).eq('id',id):db.from('bar_prodotti').insert(payload);const {error}=await q;if(error)return msg(error.message,'error');msg(id?'Proposta aggiornata.':'Proposta creata.');resetForm();loadProducts();}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$('bar-product-id').value=p.id;$('bar-product-name').value=p.nome;$('bar-product-description').value=p.descrizione||'';$('bar-product-price').value=p.prezzo;$('bar-product-order').value=p.ordine;$('bar-product-active').checked=p.attivo;window.scrollTo({top:0,behavior:'smooth'});}
async function uploadImage(id,file){if(!file?.type.startsWith('image/'))return msg('Seleziona un file immagine.','error');const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${id}/${Date.now()}.${ext}`;const current=products.find(p=>p.id===id);const oldPath=storagePathFromUrl(current?.immagine_url);const {error:upErr}=await db.storage.from('bar-immagini').upload(path,file,{upsert:true,contentType:file.type});if(upErr)return msg('Caricamento non riuscito: '+upErr.message,'error');const {data}=db.storage.from('bar-immagini').getPublicUrl(path);const {error}=await db.from('bar_prodotti').update({immagine_url:data.publicUrl}).eq('id',id);if(error)return msg(error.message,'error');if(oldPath)await db.storage.from('bar-immagini').remove([oldPath]);msg('Immagine aggiornata.');loadProducts();}
async function removeImage(id){const p=products.find(x=>x.id===id);if(!p?.immagine_url)return;const path=storagePathFromUrl(p.immagine_url);if(path)await db.storage.from('bar-immagini').remove([path]);const {error}=await db.from('bar_prodotti').update({immagine_url:null}).eq('id',id);if(error)return msg(error.message,'error');msg('Immagine eliminata.');loadProducts();}
async function deleteProduct(id){if(!confirm('Eliminare definitivamente questa proposta?'))return;await removeImage(id);const {error}=await db.from('bar_prodotti').delete().eq('id',id);if(error)return msg('Non eliminabile: '+error.message,'error');msg('Proposta eliminata.');loadProducts();}
async function loadProducts(){const {data,error}=await db.from('bar_prodotti').select('*').order('ordine').order('creato_il');if(error)return msg(error.message,'error');products=data||[];$('bar-admin-products').innerHTML=products.map(p=>`<article class="bar-admin-card"><div class="bar-admin-image drop-zone" data-id="${p.id}">${p.immagine_url?`<img src="${esc(p.immagine_url)}" alt="">`:'<span>Trascina qui una foto<br><small>o clicca per scegliere</small></span>'}<input type="file" accept="image/*" hidden></div><div class="bar-admin-info"><h3>${esc(p.nome)}</h3><p>${esc(p.descrizione||'')}</p><strong>${euro(p.prezzo)}</strong><small>Ordine ${p.ordine} · ${p.attivo?'Visibile':'Nascosta'}</small><div class="form-actions"><button class="secondary edit-product" data-id="${p.id}">Modifica</button><button class="secondary remove-image" data-id="${p.id}" ${p.immagine_url?'':'disabled'}>Elimina immagine</button><button class="danger delete-product" data-id="${p.id}">Elimina proposta</button></div></div></article>`).join('')||'<p>Nessuna proposta. Creane una con il modulo sopra.</p>';
  document.querySelectorAll('.edit-product').forEach(b=>b.onclick=()=>editProduct(b.dataset.id));document.querySelectorAll('.remove-image').forEach(b=>b.onclick=()=>removeImage(b.dataset.id));document.querySelectorAll('.delete-product').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.id));document.querySelectorAll('.drop-zone').forEach(z=>{const input=z.querySelector('input');z.onclick=()=>input.click();input.onchange=()=>uploadImage(z.dataset.id,input.files[0]);['dragenter','dragover'].forEach(ev=>z.addEventListener(ev,e=>{e.preventDefault();z.classList.add('dragging')}));['dragleave','drop'].forEach(ev=>z.addEventListener(ev,e=>{e.preventDefault();z.classList.remove('dragging')}));z.addEventListener('drop',e=>uploadImage(z.dataset.id,e.dataTransfer.files[0]));});}
async function loadBookings(){const {data,error}=await db.from('bar_prenotazioni').select('*,bar_prodotti(nome)').order('data',{ascending:false}).order('ora',{ascending:false});if(error){$('bar-bookings-body').innerHTML=`<tr><td colspan="9">${esc(error.message)}</td></tr>`;return;}$('bar-bookings-body').innerHTML=(data||[]).map(b=>`<tr><td>${new Date(b.data+'T12:00:00').toLocaleDateString('it-IT')}</td><td>${String(b.ora).slice(0,5)}</td><td>${esc(b.bar_prodotti?.nome||'—')}</td><td>${esc(b.nome_cliente)}</td><td>${esc(b.telefono)}</td><td>${b.persone}</td><td>${esc(b.note||'—')}</td><td>${esc(b.stato)}</td><td><button class="secondary cancel-booking" data-id="${b.id}" ${b.stato==='annullata'?'disabled':''}>Annulla</button></td></tr>`).join('')||'<tr><td colspan="9">Nessuna prenotazione.</td></tr>';document.querySelectorAll('.cancel-booking').forEach(x=>x.onclick=async()=>{await db.from('bar_prenotazioni').update({stato:'annullata'}).eq('id',x.dataset.id);loadBookings();});}
document.addEventListener('DOMContentLoaded',()=>{$('bar-login').onclick=login;$('bar-logout').onclick=async()=>{await db.auth.signOut();session()};$('bar-product-form').onsubmit=saveProduct;$('bar-product-reset').onclick=resetForm;$('bar-refresh-bookings').onclick=loadBookings;session();});
